### ISSUE TITLE
[Questions] Project status, usage *not* as LV2 plugin, pkgbuild

### ISSUE THREAD

**Issue by ronjouch** [Stazed/rakarrack#41]
Hi @Stazed.

Your fork works for me and addresses crashes I had with the old unmaintained rakarrack. I have two questions:

- I'm a Rakarrack-as-app user (as opposed to using it as LV2 plugins), am not familiar with LV2, and I don't understand all the preset-related issues that you opened. Do these issues impact users of the app like me, or not at all, and how "complete" is this port? Any specific broken/unported stuff, and how will I notice it? (A crash? Absence of effect? Something else?)
- I put together an Arch PKGBUILD based on the `rakarrack-git` package and adjusting it to the new build process (happy to see cmake, by the way). Any objection to publish it on the AUR?

Thanks a lot for your work 🙂.

**Comment by Stazed** [comment]
Hello ronjouch,

There are a couple of issue that should be considered before publishing.

1. Since this fork is not official, it may lead to confusion regarding the original rakarrack. It might be better to change the name to something different like rakarrack-2, or rakarrack-plus... any ideas?

2. The LV2's still contain the original rkrlv2 URI's from which they originated. These need to be changed before publishing. You can build rakarrack only by setting BuildLV2Plugins=OFF and BuildCarlaPresets=OFF.

3. Regarding the preset issues, they do not impact rakarrack. Just some additional presets that were added to the LV2's by ssj71. I plan on adding them at some point to rakarrack.

4. "how "complete" is this port"
It should be very stable. Let me know if you find something broken!
It should be compiled against FLTK >= 1.3. The original used 1.1.
On the rakarrak side (not LV2), there are no significant changes planned.
There will be a new release v0.7.2 out, pending the URI changes and potential name change. Any big changes will likely only impact the LV2's... hopefully :)

I have no objection to publishing on AUR as long as the above issues do not present any problems for users.

**Comment by ronjouch** [comment]
@Stazed 

> 1. Since this fork is not official, it may lead to confusion regarding the original rakarrack. It might be better to change the name to something different like rakarrack-2, or rakarrack-plus... any ideas?
>
> 2. The LV2's still contain the original rkrlv2 URI's from which they originated. These need to be changed before publishing. You can build rakarrack only by setting BuildLV2Plugins=OFF and BuildCarlaPresets=OFF.

Bundling these two questions together. Given that:

1. The official/original project is unmaintained (last commit is from August 2015)
2. This fork is the most taken care of: addresses crashes / leaks / bugs, adds features, modernizes build, etc.

, then do you think is it conceivable to get in touch with the original project authors and ask them to sanction this fork as the new "official" fork? (With credit given to the original project and ssj71's fork, of course). As far as I understand, there's no reason for anyone to use the original rakarrack or ssj71's instead of your fork.

- **If yes** and if the original authors agree, this project can stay rakarrack. I don't think much work/fuss is needed: minimally, a message on the original homepage saying "this fork is unmaintained, please use https://github.com/Stazed/rakarrack" would suffice. By the way, at that point, moving the fork to its own organization ( https://github.com/rakarrack/rakarrack ) would make sense. Then, with your fork established as the maintained one, I can publish an AUR package, and ping interested distributions to consider (re-)packaging it. Then about the URIs, the way LV2 URIs work isn't clear enough for me to understand. If you don't rename them, a host will not be able to differentiate this fork's plugins vs. ssj71's fork plugins, right? Is that a bad thing? How compatible are both plugins?
If you want to push this forward, but don't have so much time and want help, please ask. I could help by talking to the original authors & distros, setting up CI on commits / pull requests, and tidying up the docs. Tell me if you'd like any of these.
- **If no or if the original authors refuse / don't respond**, yeah, something with rakarrack in the name seems obvious. I don't like numbers at the end of the name, because it gets mixed with the version number: `rakarrack2-2.0` looks weird. So, `rakarrack-plus` seems fine.

> 3. Regarding the preset issues, they do not impact rakarrack. Just some additional presets that were added to the LV2's by ssj71. I plan on adding them at some point to rakarrack.

👍

> 4. "how "complete" is this port"
>    It should be very stable. Let me know if you find something broken!
>    It should be compiled against FLTK >= 1.3. The original used 1.1.
>    On the rakarrak side (not LV2), there are no significant changes planned.
>    There will be a new release v0.7.2 out, pending the URI changes and potential name change. Any big changes will likely only impact the LV2's... hopefully :)

I confirm it's stable, the presets I used to use are stable, the ones that used to crash no longer crash, and I confirm it builds with FLTK 1.3.5 (the version currently shipped by Arch).

> I have no objection to publishing on AUR as long as the above issues do not present any problems for users.

👍, keeping it local for now until the name discussion is settled.

**Comment by Stazed** [comment]
@ronjouch 

> then do you think is it conceivable to get in touch with the original project authors and ask them to sanction this fork as the new "official" fork? (With credit given to the original project and ssj71's fork, of course). As far as I understand, there's no reason for anyone to use the original rakarrack or ssj71's instead of your fork

I planned on contacting them, and it certainly should be done. I don't want to step on anyone's toes :)

> If yes and if the original authors agree, this project can stay rakarrack. I don't think much work/fuss is needed: minimally, a message on the original homepage saying "this fork is unmaintained, please use https://github.com/Stazed/rakarrack" would suffice.

Agreed.

>  By the way, at that point, moving the fork to its own organization ( https://github.com/rakarrack/rakarrack ) would make sense.

Good point. This would also solve the LV2 URI renaming issue. I would just release a final version on this repository and leave the URIs unchanged here. This would avoid ruining users projects with the original URIs. Then make the changes in the new official repository with appropriate warnings about compatibility.

> Then about the URIs, the way LV2 URIs work isn't clear enough for me to understand. If you don't rename them, a host will not be able to differentiate this fork's plugins vs. ssj71's fork plugins, right? 

Correct. Also if the plugins are installed in different locations (which they will be unless the user changes the location to be the same), it will cause duplicates which may crash some hosts.

> Is that a bad thing? How compatible are both plugins?

The plugins are mostly compatible, but...
I want to make some more substantial changes involving consistency between rakarrak and the LV2s. These changes will not be backward compatible or compatible with the originals from ssj71. Changing to a new repository would be the time to do this. These changes will not impact rakarrack.

>  I could help by talking to the original authors & distros, setting up CI on commits / pull requests, and tidying up the docs. Tell me if you'd like any of these.

All the above would be great. Time will be an issue until mid to late February. As it stands, if no name change is needed, rakarrack should be ready to go. The LV2s should not be packaged until the changes are made. It should not take me more than a couple of weeks to update them. I will set the default to not build them until they are ready.

If you could find out about the naming issue, I will set up the new repository and move things. 

btw: The latest for this project is in the wip (work in progress) branch. There are about a dozen commits that are ready for release which would be included in a final v0.7.2 here. Included is the new FLTK gleam theme which looks great!

Thanks!

**Comment by ronjouch** [comment]
@Stazed

> I would just release a final version on this repository and leave the URIs unchanged here. This would avoid ruining users projects with the original URIs. Then make the changes in the new official repository with appropriate warnings about compatibility.

Great idea.

> [Help with communication, CI, docs] would be great. Time will be an issue until mid to late February. As it stands, if no name change is needed, rakarrack should be ready to go. The LV2s should not be packaged until the changes are made. It should not take me more than a couple of weeks to update them. I will set the default to not build them until they are ready.

Sounds good.

> btw: The latest for this project is in the `wip` (work in progress) branch. There are about a dozen commits that are ready for release which would be included in a final v0.7.2 here. Included is the new FLTK gleam theme which looks great!

Cool! Branch `wip` tested, builds and works for me.

> If you could find out about the naming issue, I will set up the new repository and move things.

Okay. Tomorrow Sunday or next week, I will get in touch with the original project, summarize what we said here, and point to our discussion here. Will do my best to "not step on anyone's toes", like you said, while articulating my thoughts as a user (old fork unmaintained, this fork healthier, no reason to let users use the old one and miss this fork's fixes & improvements). This is delicate, so below is a draft, please review it and share your feedback.

Finally, writing the message below raised a new question: what about ssj71? I'm asking because, while I'm writing here as a result of your fork being (as far as I understand) the most mature, ssj71 is the original author of the LV2 port. So, out of respect for their work and for the health of the project, it would feel weird to establish a new org and not include them in it.

1. Did you ever get in touch with them?
2. Are you okay to include them in this discussion? Can I ask for attention here with an @mention?
3. I see a few recent commits in https://github.com/ssj71/rkrlv2/commits/master , do you see anything pertinent to bring to your fork?
4. If ssj71 is on board with us here and working on a shared https://github.com/rakarrack/rakarrack , would that change your plans for LV2 backward-incompatible changes & URIs? Are your changes irreconciliable?

---

**Proposal for message to original Rakarrack maintainers**

Hi Rakarrack maintainers :)

I've been using rakarrack for a few years. Recently, as I was setting up a new sound card & machine, I took the time to review music software I was using, including Rakarrack. I found out that:

1. Rakarrack 0.6.1 is unstable for me, often crashing at startup and sometimes at runtime.

2. The official Rakarrack project is unmaintained (last commit is from August 2015, 4.5 years ago as of January 2020).

3. There are a few interesting forks:
    1. https://github.com/ssj71/rkrlv2 is a fork of 0.6.1, porting it to LV2 plugins.
    2. https://github.com/Stazed/rakarrack is based on the above port, plus lots of bugfixes, memory leak fixes based on Valgrind, and improvements. I haven't had a single crash with this fork.

As a user, I see no reason to miss out on ssj71 & Stazed work, and I think their work deserves more visibility.

Also, using SourceForge remains doable, but it's clunky compared to e.g. GitHub or GitLab, so I understand ssj71 & Stazed not being thrilled by the perspective of merging their work on SourceForge and keeping using it.

For these reasons, Stazed & I would like to know if you would accept to declare rakarrack.sourceforge.net dead, and point (through a message on the home page) visitors to use Stazed's maintained fork. The whole discussion between Stazed & I is public at https://github.com/Stazed/rakarrack/issues/41 . In summary, we'd like to:

- Create a rakarrack organization on GitHub, and move https://github.com/Stazed/rakarrack to https://github.com/rakarrack/rakarrack , with initial commit bits to you, Stazed, ssj71.
- Release a last version of Stazed/rakarrack keeping the LV2 URIs inherited from ssj71's.
- Release a first "official LV2 version" using new LV2 URIs.
- Get in touch with packagers, asking them to (re-)package the newly-official fork.

I sincerely hope I'm not bruising anyone here. I'm doing this because I was glad to find out about the maintained forks, and would enjoy to give back to the community by helping stabilize & spread work that has been useful to me.

Thanks for all the work on rakarrack!

**Comment by Stazed** [comment]
@ronjouch 

First, let me apologize for what is to come... sorry!

After a sleepless night, I have come to the conclusion that I do not want to become the official maintainer of rakarrack, or rakarrack-plus or the maintainer of any published project that could be as popular as rakarrack. I looked at the sourceforge downloads for rakarrack version 6.1, last updated November 2010. There were 52 downloads a week. That is for an unstable, unmaintained, unfinished, bug infested ten year old program. I mean no disrespect to anyone, I loved that program.
So did many others, and still do. Coming out with a newer stable cleaned up version, which this is, could be very popular. And with great popularity comes great responsibility and many, many more problems. I am not responsible enough for the job, nor do I wish to be.

The reason I did this project was that I loved rakarrack and the LV2s were a great idea.  But version 6.2 of rakarrack killed it. And the reasons that killed rakarrack were imported into ssj71's LV2s. Most of the original LV2s crashed, produced no sound, or sounded completely different from rakarrack.
So I came across ssj71s incomplete merge and took a shot at finishing it. And here we are. I now have a stable working rakarrack and some great LV2s, for my own personal music interests. I did not do this for credit, and to be perfectly honest, the community. I keep a low profile because I have seen what the maintainers of popular projects have to deal with and I don't have the patience for that.

So, this is what I am going to do. A final version of this repository will be released in the next few weeks. I will create a new repository using https://github.com/Stazed/rakarrack-plus. Work will continue there and I will change the LV2 URIs there.

I do not want this repository or the new one to be published. You can, but if it becomes a hassle for me then I will discontinue working on it and move to a private repository. If it becomes a really really big hassle, I will remove it.

But, here is what you can do if you want the responsibility.. fork it. Talk to the original developers about the name if you want or even use rakarrack-plus or any other name you want. You have my blessings and thanks. I am sure everyone would be very happy and thank you. Don't get me wrong, I love open source and maintain this and several other revived projects. But maintaining a popular published project which a new rakarrack would likely be is beyond my capacity.

If you do decide to fork this project and maintain it yourself, or can get someone else to do it, let me know. The reason is that the LV2 URIs need to be changed and if an official new project is created, they should be based on that repository address.

Again, my apologies for the reversal on this. 

Good luck...

**Comment by ronjouch** [comment]
@Stazed apologies accepted. I'm 100% okay with your decision and am thankful you put the brakes on rather sooner than later.

I'll fork at some point if necessary; as of today, your fork as it is works great for my needs, and I don't have anything to ask for. As to carrying myself the full technical weight of what I wanted us to do, I'll think about it but am not sure I have the technical chops (I'm not super proficient with C/C++), which would lead to the weird situation of barely being to drive the car I jumped in.

Will keep using your fork(s), will keep the Arch PKGBUILD for myself to avoid drawing attention, may come back once-in-a-blue-moon with an issue report or feature request.

Cheers and thanks again for your work 🙂. Closing.
